services:
  publisher:
    build: ./src/publisher
    container_name: publisher
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy

  # worker service to process messages from SQS
  worker:
    build: ./src/worker
    container_name: worker
    env_file:
      - .env
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-test}
      - AWS_ENDPOINT_URL=http://localstack:4566
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    depends_on:
      publisher:
        condition: service_healthy

  # https://docs.localstack.cloud/references/configuration/
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"           # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG:-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      ##- SERVICES=${SERVICES:-sts,sqs,sns,dynamodb,ec2}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
