services:
  publisher:
    build: ./src/publisher
    container_name: publisher
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - PORT=8000
      - TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:pub-sub
    depends_on:
      localstack:
        condition: service_healthy

  # worker service to process messages from SQS
  worker:
    build: ./src/worker
    container_name: worker
    restart: always
    env_file:
      - .env
    environment:
      - QUEUE_URL=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/pub-sub
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    depends_on:
      publisher:
        condition: service_healthy

  # https://docs.localstack.cloud/references/configuration/
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"           # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG:-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      ##- SERVICES=${SERVICES:-sts,sqs,sns,dynamodb,ec2}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
