services:
  flask-app:
    build: .
    container_name: flask-app
    volumes:
      - $HOME/.aws/credentials:/home/nonroot/.aws/credentials:ro
    ports:
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - TABLE_NAME=foo
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
