name: Pylint

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/publisher/**'
      - 'src/subscriber/**'
      - '.github/workflows/pylint.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest flake8
          pip install -r ./src/publisher/requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
