name: 'Terraform Unit Tests'

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/tf-unit-tests.yml'
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  release:
    types: [published]

env:
  DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: localstack
  AWS_SECRET_ACCESS_KEY: localstack

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:light
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff
        working-directory: ./terraform

  terraform-unit-tests:
    runs-on: ubuntu-latest
    needs: terraform-ci
    container: hashicorp/terraform:light

    permissions:
      # required for all workflows
      security-events: write

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set common environment variables
        run: cat ../.github/.env >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan (mocked)
        if: github.event_name == 'pull_request'
        run: |
          cp -f ../tests/fixtures/localstack/versions.tf versions.tf
          cp -f ../tests/fixtures/fixtures.tfvars .
          terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform

      - name: Upload SARIF file
        if: github.ref == 'refs/heads/main' && success()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: checkov
